# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: install required packages for ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 build-essential libgtk-3-dev libsdl2-ttf-2.0-0 libportaudio2
        pip install -U  -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Install and configure X window with virtual screen
        sudo apt-get install xserver-xorg libglu1-mesa-dev freeglut3-dev mesa-common-dev libxmu-dev libxi-dev
        # Configure the nvidia-x
        sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024
        # Run the virtual screen in the background (:0)
        sudo /usr/bin/X :0 &
        # We only need to setup the virtual screen once

        # Run the program with vitural screen

        # If you dont want to type `DISPLAY=:0` everytime
        export DISPLAY=:0
        pytest
